# Basic workflow

name : Getting Started

# Controls when the action will run
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Step represents a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access with:
      - uses: actions/checkout@v2

      # Runs a singe command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 01. What is in this directory?
          ls -a
          echo
          echo 02. Is Java installed?
          java --version
          echo
          echo 03. Is Git installed?
          git --version
          echo
          echo 04. What about build tools?
          mvn --version
          gradle --version
          ant -version
          echo
          echo 05. Where is the Android SDK Root?
          echo $ANDROID_SDK_ROOT
          echo
          echo 06. Where are the Selenium jars?
          echo $SELENIUM_JAR_PATH
          echo
          echo 07. What is the Workspace location?
          echo $RUNNER_WORKSPACE
          echo
          echo 08. Who is running this script?
          whoami
          echo 09. How is the dic laid out?
          df
          echo 10. What environment variables are available?
          env