# Basic workflow

name : Getting Started

# Controls when the action will run
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Step represents a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access with:
      - uses: actions/checkout@v2

      # Runs a singe command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo This is a multi-line script
          echo directly written in the .yml file