# Basic workflow for GitHub Actions

name : Simple GitHub Actions

# Controls when the action will run
on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Step represents a sequence of tasks that will be executed as part of the job
    steps:
      # Pre-build disc space
      - name: Step 1 - Pre-build disc space
        run: df

      # Checkout to develop Project Branch
      - name: Step 2 - Checkout to "develop"
        uses: actions/checkout@v2

      # Runs a singe command using the runners shell
      - name: Step 3 - Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Step 4 - Run a multi-line script
        run: |
          echo This is a multi-line script
          echo directly written in the .yml file

      # Runs the shell script
      - name: Step 5 - Run the shell script
        run: sh ./github-action-script.sh

      # Set up JDK
      - name: Step 6 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # Build Jakarta WebApp with Maven
      - name: Step 7 - Jakarta WebApp
        run: echo mvn -B package --file pom.xml

      # Post-build disc space
      - name: Step 8 - Post-build disc space
        run: df