# Workflow for three different environments

name: Workflow - Three environment

on:
  push:
    branches: [ main ]

jobs:
  # First job to run
  DEV:
    name: Starting - Three environment (DEV)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest]
        python-version: [ '3.9', '3.10']

    environment: DEV

    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v2

      - name: Step 2 - Run a script
        run: |
          echo "I am running a job in the DEV environment"

      - name: Step 3 - Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

  # Second job to run
  QA:
    name: Starting - Three environment (QA)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ '3.9', '3.10' ]

    environment: QA

    needs: DEV

    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v2

      - name: Step 2 - Run a script
        run: |
          echo "I am running a job in the QA environment"

      - name: Step 3 - Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

  # Third job to run
  PROD:
    name: Starting - Three environment (PROD)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ '3.9', '3.10' ]

    environment: PROD
    needs: QA

    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v2

      - name: Step 2 - Run a script
        run: |
          echo "I am running a job in the PROD environment"

      - name: Step 3 - Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
